dist: bionic
sudo: required

language: generic

addons:
  apt:
    update: true
    packages:
      - jam
      - binutils-mingw-w64-i686
      - gcc-mingw-w64-i686
      - g++-mingw-w64-i686
      - gcc-6
      - g++-6
      - libsdl2-dev
      - libsdl2-mixer-dev
      - libspeechd-dev
      - qtbase5-dev
      - qtbase5-dev-tools

script:
  - jam -dx -sC++=$CXX -sCC=$CC -sMOC=/usr/lib/qt5/bin/moc -sUSETTS=yes -j4

matrix:
  include:
    # MinGW - No SDL for now because sdl2_mixer isn't available
    - env: CC=i686-w64-mingw32-gcc CXX=i686-w64-mingw32-g++ OS=MINGW MINGWARCH=i686-w64-mingw32 CROSS=1 USESDL=no
    # GCC
    - env: CC=gcc-6 CXX=g++-6
    - env: CC=gcc-7 CXX=g++-7
    # Clang
    - env: CC=clang CXX=clang++
