name: Fedora packages

on:
  push:
  pull_request:

jobs:
  build:
    name: Fedora ${{ matrix.version }} package
    strategy:
      matrix:
        version:
          - 33
          - 34
          - 35

    runs-on: ubuntu-20.04
    container:
      image: fedora:${{ matrix.version}}

    steps:
      - run: |
          yum -y update
          yum -y install SDL2-devel SDL2_mixer-devel cmake fontconfig-devel freetype-devel libjpeg-turbo-devel libpng-devel qt5-qtbase-devel rpm-build

      - uses: actions/checkout@v2

      - name: Build RPM
        run: ./gargoyle-buildrpm.sh

      - name: Upload artifact
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v2
        with:
          name: Gargoyle-Fedora-${{ matrix.version }}
          path: ~/rpm_factory/RPMS/x86_64/*.rpm
