name: macOS (Qt)

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update brew
        run: brew update

      - name: Install packages
        # XXX Work around a bug in the Mac runner where install returns false.
        # This will also cause legitimate installations to signal success, so should be removed as soon as the runner is fixed.
        run: brew install libopenmpt libsndfile libvorbis mpg123 qt6 libpng jpeg || true

      - name: Build (Qt)
        run: |
          mkdir build-cmake
          cd build-cmake
          cmake .. -DINTERFACE=QT -DSOUND=QT -DWITH_QT6=ON -DCMAKE_FIND_FRAMEWORK=LAST
          make -j`sysctl -n hw.ncpu`
