name: macOS

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update brew
        run: brew update

      - name: Install packages
        run: brew install sdl2 sdl2_mixer libvorbis jam

      - name: Build (CMake)
        run: |
          mkdir build
          cd build
          cmake ..
          make -j`sysctl -n hw.logicalcpu`
          make install

      - name: Build (legacy Jam)
        run: sh gargoyle_osx.sh
