name: macOS

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update brew
        run: brew update

      - name: Install packages
        run: brew install libopenmpt libsndfile libvorbis mpg123 qt6 sdl2 sdl2_mixer

      - name: Build
        run: sh gargoyle_osx.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Gargoyle.dmg
          path: gargoyle*.dmg

      - name: Build (Qt)
        run: |
          mkdir build-cmake
          cd build-cmake
          cmake .. -DINTERFACE=QT -DSOUND=QT -DWITH_QT6=ON
          make -j`sysctl -n hw.ncpu`
