name: macOS

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update brew
        run: brew update

      - name: Install packages
        run: brew install sdl2 sdl2_mixer libvorbis jam

      - name: Build
        run: sh gargoyle_osx.sh

      - name: Build (legacy Jam)
        run: jam -sUSETTS=yes -sBUNDLEFONTS=no -sMAC_USEHOMEBREW=yes -sMACOS_MIN_VER=10.9 -j`sysctl -n hw.ncpu`
