name: MinGW

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        arch:
          - i686
          - x86_64

    runs-on: ubuntu-20.04
    container:
      image: amd64/ubuntu:20.04
      options: --privileged

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update packages
        run: apt update

      - name: Install packages
        run: DEBIAN_FRONTEND=noninteractive apt install -y
          build-essential
          cmake
          g++-mingw-w64
          gcc-mingw-w64
          git
          mingw-w64-tools
          nsis
          p7zip-full
          unzip
          wget

      - name: Set up MinGW environment
        run: |
          update-alternatives --set ${{ matrix.arch }}-w64-mingw32-gcc /usr/bin/${{ matrix.arch }}-w64-mingw32-gcc-posix
          update-alternatives --set ${{ matrix.arch }}-w64-mingw32-g++ /usr/bin/${{ matrix.arch }}-w64-mingw32-g++-posix
          wget https://github.com/garglk/assets/raw/master/mingw/mingw-${{ matrix.arch }}.tar.xz
          tar xfv mingw-${{ matrix.arch }}.tar.xz -C /
          mkdir NSIS
          cd NSIS
          wget https://nsis.sourceforge.io/mediawiki/images/7/78/FontName-0.7.zip
          unzip FontName-0.7.zip
          7z x -bb3 FontName-0.7.exe
          mkdir -p /usr/share/nsis/Include
          mkdir -p /usr/share/nsis/Plugins/x86-ansi
          for inc in Include/*; do iconv -f CP1251 -t UTF8 ${inc} -o /usr/share/nsis/Include/$(basename ${inc}); done
          cp Plugins/FontName.dll /usr/share/nsis/Plugins/x86-ansi
          cd ..

      - name: Set environment variables
        run: |
          echo "GARGOYLE64=1" >> $GITHUB_ENV
        if: ${{ matrix.arch == 'x86_64' }}

      - name: Build
        run: ./windows.sh

      - name: Upload installer
        uses: actions/upload-artifact@v2
        with:
          name: Gargoyle-${{ matrix.arch }}
          path: gargoyle-*.exe
